const path = "/models";

export const modelDescriptors = [
	{
		src: `${path}/platform/source/model.fbx`,
		id: "platform",
		animated: false,
		type: "fbx",
		material: "subsurface",
		color: "#f4b5cd",
		scale: 0.05,
	},
	{
		src: `${path}/hair/source/model.glb`,
		id: "hair",
		animated: false,
		type: "gltf",
		material: "standard",
		color: "#000000",
		scale: 5,
	},
	{
		src: `${path}/bump/source/model.fbx`,
		id: "bump",
		animated: false,
		type: "fbx",
		material: "subsurface",
		color: "#f4b5cd",
		scale: 0.05,
	},
	{
		src: `${path}/souture/source/model.glb`,
		id: "souture",
		animated: false,
		type: "gltf",
		material: "metal",
		color: "#000000",
		scale: 5,
	},
	{
		src: `${path}/knife/source/model.glb`,
		id: "knife",
		animated: true,
		type: "gltf",
		material: "metal",
		color: "#d1d1d1",
		scale: 5,
	},
	{
		src: `${path}/montagneRusse/source/model.glb`,
		id: "montagneRusse",
		animated: false,
		type: "gltf",
		material: "metal",
		color: "#d1d1d1",
		scale: 5,
	},
	{
		src: `${path}/dentWagon1/source/model.glb`,
		id: "dentWagon1",
		animated: true,
		type: "gltf",
		material: "toothrail",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/dentWagon2/source/model.glb`,
		id: "dentWagon2",
		animated: true,
		type: "gltf",
		material: "toothrail",
		color: "#ffffff",
		scale: 5,
	},
	{
		src: `${path}/dentWagon3/source/model.glb`,
		id: "dentWagon3",
		animated: true,
		type: "gltf",
		material: "toothrail",
		color: "#ffffff",
		scale: 5,
	},
	{
		src: `${path}/dentWagon4/source/model.glb`,
		id: "dentWagon4",
		animated: true,
		type: "gltf",
		material: "toothrail",
		color: "#ffffff",
		scale: 5,
	},
	{
		src: `${path}/earGuy/source/model.glb`,
		id: "earGuy",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#ffffff",
		scale: 5,
	},
	{
		src: `${path}/hand/palm/source/model.glb`,
		id: "handpalm",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/hand/finger1/source/model.glb`,
		id: "handfinger1",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/hand/finger2/source/model.glb`,
		id: "handfinger2",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/hand/finger3/source/model.glb`,
		id: "handfinger3",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/hand/finger4/source/model.glb`,
		id: "handfinger4",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/hand/finger5/source/model.glb`,
		id: "handfinger5",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/guirlande/source/model.glb`,
		id: "guirlande",
		animated: true,
		type: "gltf",
		material: "guirlande",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/porte1/source/model.glb`,
		id: "porte1",
		animated: true,
		type: "gltf",
		material: "none",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/eyeFollow/source/model.glb`,
		id: "eyeFollow",
		animated: true,
		type: "gltf",
		material: "none",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/eyeUP/source/model.glb`,
		id: "eyeUP",
		animated: true,
		type: "gltf",
		material: "none",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/clamp/source/model.glb`,
		id: "clamp",
		animated: true,
		type: "gltf",
		material: "none",
		color: "#00ff00",
		scale: 5,
	},
	{
		src: `${path}/humanorium/stand/source/model.glb`,
		id: "humanstand",
		animated: true,
		type: "gltf",
		material: "metal",
		color: "#f4b5cd",
		scale: 5,
	},
	{
		src: `${path}/humanorium/helice1/source/model.glb`,
		id: "humanhelice1",
		animated: true,
		type: "gltf",
		material: "metal",
		color: "#f4b5cd",
		scale: 5,
	},
	{
		src: `${path}/humanorium/helice2/source/model.glb`,
		id: "humanhelice2",
		animated: true,
		type: "gltf",
		material: "metal",
		color: "#f4b5cd",
		scale: 5,
	},
	{
		src: `${path}/coiler/source/model.glb`,
		id: "coiler",
		animated: true,
		type: "gltf",
		material: "metal",
		color: "#f4b5cd",
		scale: 5,
	},
	{
		src: `${path}/toupie/toupie/source/model.glb`,
		id: "touptoupie",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#f4b5cd",
		scale: 5,
	},
	{
		src: `${path}/toupie/socle/source/model.glb`,
		id: "toupsocle",
		animated: true,
		type: "gltf",
		material: "skin",
		color: "#f4b5cd",
		scale: 5,
	},
];

export const buttonDescriptors = [
	{
		src: `${path}/tooth1/source/model.fbx`,// pink
		id: "tooth1",
		type: "fbx",
		material: "tooth",
		color: "#edb9de",
		scale: 0.05,
	},
	{
		src: `${path}/tooth2/source/model.fbx`, // orange
		id: "tooth2",
		type: "fbx",
		material: "tooth",
		color: "#e8d295",
		scale: 0.05,
	},
	{
		src: `${path}/tooth3/source/model.fbx`, // green
		id: "tooth3",
		type: "fbx",
		material: "tooth",
		color: "#ceedce",
		scale: 0.05,
	},
	{
		src: `${path}/tooth4/source/model.fbx`, // blue
		id: "tooth4",
		type: "fbx",
		material: "tooth",
		color: "#bfc4f2",
		scale: 0.05,
	},
	{
		src: `${path}/tooth5/source/model.fbx`, 	// red
		id: "tooth5",
		type: "fbx",
		material: "tooth",
		color: "#f29c96",
		scale: 0.05,
	},
	{
		src: `${path}/tooth6/source/model.fbx`, // black
		id: "tooth6",
		type: "fbx",
		material: "tooth",
		color: "#696261",
		scale: 0.05,
	},
]
